#!/usr/bin/env node

//must run as sudo

var fs = require("fs");
var exec = require('child_process').exec;
                                               
var config = {

	'appName': 'mySuperApp',
	'systemAction': '/home/master/system/script/system/action',
	'repoName': 'AaronDavisG/myApp',
	'repoURL': 'https://github.com',
	'repoEXT':'git',
	'user':'master',
	'group':'master',
	'access':755,
	'port': process.env.PORT || 8080,
	'database': 'mongodb://localhost:27017/myDatabase',
	'databasePromise': 'bluebird',
	'secret': 'mySecret'
}

function dataPrompt(data, callback){

	var index = 0;
	var keys = Object.keys(data);
	var size = keys.length;

	if ( size > 0 ){

		var key = keys[index];
		var value = data[key];

		console.log('input ' + keys[index] );
		console.log('  defaultValue: ' + data[key]);
		
		process.stdin.resume();

		process.stdin.setEncoding('utf8');

		process.stdin.on('data', function (text) {

			if (text.length > 1){

				text = text.slice(0, text.length - 1);

				if (Number.isInteger(text)){

					data[key] = parseInt(text, 10);

				}else if( !isNaN(parseFloat(text)) ){

					data[key] = parseFloat(text);
				}else{
					data[key] = text;
				}
			}
			index++;

			if (index == size){
			//	process.stdin.resume();
				callback(null, data);
			}else{
				key = keys[index];
				value = data[key];

				console.log('input ' + keys[index]);
				console.log('  defaultValue: ' + data[key]);
			}
		});
	}
}

function deleteFolder(fs, path){

	if( fs.existsSync(path) ) {
	
		fs.readdirSync(path).forEach(function(file,index){
	
			var curPath = path + "/" + file;

			if(fs.lstatSync(curPath).isDirectory()) {
				
				deleteFolder(fs, curPath);
			} else {
				fs.unlinkSync(curPath);
			}
		});
		fs.rmdirSync(path);
	}
}

function cloneRepo(exec, systemAction, dirName, repoName, repoURL, repoEXT, callback){

	exec(config.systemAction
		+ ' git cloneRepo '
		+ dirName + ' '
		+ repoName + ' '
		+ repoURL + ' '
		+ config.repoEXT,
		function (error, stdout, stderr) {

			console.log(stdout);

			if (error) {
				
				console.log('exec error: ' + error);
			} else {
				console.log('repo: ' + repoURL + '/' + repoName + '.' + repoEXT 
					+ ' cloned to: ' + dirName);
			}
			callback(error);
		}
	);
}

function install(fs, exec, config, callback){

	dataPrompt(config,
		function(error, config){
		
			if (error) {
				process.exit(1);
			}
			var appDir = process.cwd() + '/' + config.appName;

			deleteFolder(fs, appDir);

	    	fs.mkdirSync(appDir);

	 		cloneRepo(exec, 
	 			config.systemAction,
	 			process.cwd() + '/' + config.appName, 
	 			config.repoName,
	 			config.repoURL,
	 			config.repoEXT,
				function(error){

					if (error) {
						process.exit(1);
					}
					var util = require('./' + config.appName + '/util');

					util.writeExports(fs,
						appDir + '/config.js',
						config,
						function(error){
					
							if (error) {
								process.exit(1);
							}
							var systemServicePath = '/lib/systemd/system/' + config.appName + '.service';

							var systemService = '';

							systemService = systemService + '[Unit]\n'
							systemService = systemService + 'Description=Node.js ' + config.appName + '\n'
							systemService = systemService + 'Requires=After=mongod.service\n'
							systemService = systemService + '[Service]\n'
							systemService = systemService + 'ExecStart=/usr/local/bin/node ' + process.cwd() + '/server.js\n'
							systemService = systemService + 'Restart=always\n'
							systemService = systemService + 'RestartSec=10\n'
							systemService = systemService + 'User='+ config.user + '\n'
							systemService = systemService + 'Group='+ config.group + '\n'
							systemService = systemService + 'StandardOutput=syslog\n'
							systemService = systemService + 'StandardError=syslog\n'
							systemService = systemService + 'SyslogIdentifier=nodejs-' + config.appName + '\n'
							systemService = systemService + 'Environment=NODE_ENV=production PORT=' + config.port +'\n'

							systemService = systemService + '[Install]\n'
							systemService = systemService + 'WantedBy=multi-user.target\n'

							util.write(fs,
								systemServicePath,
								systemService,
								function(error){
											
									if (error) {
										process.exit(1);
									}
									util.npmInstall(exec,
										appDir,
										function(error){

											if (error) {
												process.exit(1);
											}
											util.setPermission(exec, 
												appDir,
												config.owner,
												config.group,
												config.access,
												function(error){

													if (error) {
														process.exit(1);
													}
													console.log(config.appName + ' install success');

													fs.unlinkSync(__filename);

													callback(error);
												}
											);
										}
									);
								}
							);
						}
					);
				}
			);
		}
	);
}

install(fs,
	exec,
	config,
	function(error){
		console.log('done');
		process.exit(0);
	}
);
