#!/usr/bin/env node

var fs = require("fs");
var exec = require('child_process').exec;

var config = {

	'appName': 'mySuperApp',
	'systemAction': '/home/master/system/script/system/action',
	'repoName': 'AaronDavisG/myApp',
	'repoURL': 'https://github.com',
	'repoEXT':'git',
	'port': process.env.PORT || 8080,
	'database': 'mongodb://localhost:27017/myDatabase',
	'databasePromise': 'bluebird',
	'secret': 'mySecret'
}

function objectPrompt(targetObject, next){

	var targetIndex = 0;
	var targetKeys = Object.keys(targetObject);
	var targetSize = targetKeys.length;

	if ( targetSize > 0 ){

		var key = targetKeys[targetIndex];
		var value = targetObject[key];

		console.log('input ' + targetKeys[targetIndex] );
		console.log('  defaultValue: ' + targetObject[key]);
		process.stdin.resume();

		process.stdin.setEncoding('utf8');

		process.stdin.on('data', function (text) {

			if (text.length > 1){

				text = text.slice(0, text.length - 1);

				if (Number.isInteger(text)){

					targetObject[key] = parseInt(text, 10);

				}else if( !isNaN(parseFloat(text)) ){

					targetObject[key] = parseFloat(text);
				}else{
					targetObject[key] = text;
				}
			}
			targetIndex++;

			if (targetIndex == targetSize){

				process.stdin.resume();

				next();
			}else{

				key = targetKeys[targetIndex];
				value = targetObject[key];

				console.log('input ' + targetKeys[targetIndex] );
				console.log('  defaultValue: ' + targetObject[key]);
			}
		});
	}
}

function deleteFolder(fs, path){
	
	if( fs.existsSync(path) ) {
	
		fs.readdirSync(path).forEach(function(file,index){
	
			var curPath = path + "/" + file;
			
			if(fs.lstatSync(curPath).isDirectory()) { // recurse
				
				deleteFolder(fs, curPath);
			} else { // delete file
				fs.unlinkSync(curPath);
			}
		});
		fs.rmdirSync(path);
	}
}

function cloneRepo(config, exec, next){

	var dirName = process.cwd() + '/' + config.appName;
	var repoName = config.repoName
	var repoURL = config.repoURL
	var repoEXT = config.repoEXT

	var execCommand = config.systemAction + ' git cloneRepo ' + dirName + ' ' + repoName + ' ' + repoURL + ' ' + repoEXT;

	var execCallback = function (error, stdout, stderr) {

		console.log(stdout);

		if (error == null) {
			console.log('repo: ' + repoURL + '/' + repoName + '.' + repoEXT + 
						' cloned to: ' + dirName);

			next();
		} else {
			console.log('exec error: ' + error);

			process.exit(1);
		}
	}
	exec(execCommand, execCallback);
}

function writeExportObject(fs, path, exportObject, next){

	var writeObject = 'module.exports = ' + JSON.stringify(exportObject, null, 2) + ';\n';

	console.log(writeObject);

	fs.writeFile(path, writeObject, function(error) {
		
		if (error) {
			console.log("write error:  " + error.message);
		} else {
			console.log("Successful Write to " + path);
		}
		next();
	});
}

function installModules(exec, path, next){

	var execCommand = 'cd ' + path + ' && npm install';

	var execCallback = function (error, stdout, stderr) {

		console.log(stdout);

		if (error == null) {
			console.log('npm install success');

			next();
		} else {
			console.log('npm install error: ' + error);

			process.exit(1);
		}
	}
	exec(execCommand, execCallback);
}

function install(fs, exec, config){

	objectPrompt(config, function(){
		
		var appDir = process.cwd() + '/' + config.appName;

		deleteFolder(fs, appDir);

    	fs.mkdirSync(appDir);
 
		cloneRepo(config, exec, function(){

			writeExportObject(fs, appDir + '/config.js', config, function(){

				installModules(exec, appDir, function(){

					console.log(config.appName + ' install success');

					// add delete install here

					process.exit(0);
				});
			});
		});
	});
}

install(fs, exec, config);
