#!/usr/bin/env node

//must be run as sudo

function reset(exec, callback){

	console.log('starting reset: process ' + process.pid);

	console.log('starting reset stop');

	exec(__dirname + '/stop',
		function (error, stdout, stderr) {

			if(stdout){
				if (stdout.length > 1){
					stdout = stdout.slice(0, stdout.length - 1);
				}
				console.log(stdout);
			}
			if (error) {
				console.log('reset stop error' );
			} else {
				console.log('reset stop success');
			}
			console.log('starting reset start');

			exec(__dirname + '/start',
				function (error, stdout, stderr) {

					if(stdout){
						if (stdout.length > 1){
							stdout = stdout.slice(0, stdout.length - 1);
						}
						console.log(stdout);
					}
					if (error) {
						console.log('reset start error: process ' + process.pid + ' exit' );
						process.exit(1);
					} else {
						console.log('reset start success');
					}
					console.log('reset success');

					callback(error);
				}
			);
		}
	);
}

reset(require('child_process').exec,
	function(error){

		if(error){
			console.log('error: process ' + process.pid + ' exit');
			process.exit(1);
		}else{
			console.log('success: process ' + process.pid + ' exit');
			process.exit(0);
		}
	}
);
