#!/usr/bin/env node

//must be run as sudo

function start(exec, util, config, callback){

	console.log('starting start: process ' + process.pid);

	console.log('starting start systemServiceReload');

	util.systemServiceReload(exec,
		function(error){

			if (error) {
				console.log('start systemServiceReload error: process ' + process.pid + ' exit');
				process.exit(1);
			}else{
				console.log('start systemServiceReload success');
			}
			console.log('starting start systemServiceCall enable');

			util.systemServiceCall(exec,
				config.appName,
				'enable',
				function(error){
			
					if (error) {
						console.log('start systemService enable error: process ' + process.pid + ' exit');
						process.exit(1);
					}else{
						console.log('start systemService enable success');
					}
					console.log('starting start systemServiceCall start');

					util.systemServiceCall(exec,
						config.appName,
						'start',
						function(error){
					
							if (error) {
								console.log('start systemService start error: process ' + process.pid + ' exit');
								process.exit(1);
							}else{
								console.log('start systemService start success');

								console.log('starting success');
							}
							callback(error);
						}
					);
				}
			);
		}
	);
}

start(require('child_process').exec,
	require('./util'),
	require('./config.js'),
	function(error){

		if(error){
			console.log('error: process ' + process.pid + ' exit');
			process.exit(1);
		}else{
			console.log('success: process ' + process.pid + ' exit');
			process.exit(0);
		}
	}
);
