#!/usr/bin/env node

//must be run as sudo

var exec = require('child_process').exec;
var util = require('./util');
var config = require('./config.js');

function start(exec, util, config, callback){

	util.systemServiceReload(exec,
		function(error){

			if (error) {
				console.log('start systemServiceReload error');
				process.exit(1);
			}else{
				console.log('start systemServiceReload success');
			}
			util.systemServiceCall(exec,
				config.appName,
				'enable',
				function(error){
			
					if (error) {
						console.log('start systemService enable error');
						process.exit(1);
					}else{
						console.log('start systemService enable success');
					}
					util.systemServiceCall(exec,
						config.appName,
						'start',
						function(error){
					
							if (error) {
								console.log('start systemService start error');
								process.exit(1);
							}else{
								console.log('start systemService start success');
							}
							callback(error);
						}
					);
				}
			);
		}
	);
}

start(exec,
	util,
	config,
	function(error){

		if(error){
			console.log('start error: ' + error);

			process.exit(1);
		}else{
			console.log('start success')
			
			process.exit(0);
		}
	}
);













/**
#create systemd service file
echo "[Unit]
Description=High-performance, schema-free document-oriented database
After=network.target
 
[Service]
Type=forking
User=$user
Group=$group
PIDFile=$pidPath
ExecStart=/usr/bin/mongod --quiet --config /etc/mongod.conf

[Install]
WantedBy=multi-user.target" > /lib/systemd/system/mongod.service



systemctl daemon-reload

systemctl enable mongod.service

*/
