#!/usr/bin/env node

//must be run as sudo

function stop(exec, util, config, callback){
	
	console.log('starting stop: process ' + process.pid);

	console.log('starting stop systemServiceCall disable');

	util.systemServiceCall(exec,
		config.appName,
		'disable',
		function(error){
	
			if (error) {
				console.log('stop systemServiceCall disable error: process ' + process.pid + ' exit');
				process.exit(1);
			}else{
				console.log('stop systemServiceCall disable success');
			}
			console.log('starting stop systemServiceCall stop');

			util.systemServiceCall(exec,
				config.appName,
				'stop',
				function(error){
			
					if (error) {
						console.log('stop systemServiceCall stop error: process ' + process.pid + ' exit');
						process.exit(1);
					}else{
						console.log('stop systemServiceCall stop success');

						console.log('stop success');
					}
					callback(error);
				}
			);
		}
	);
}

stop(require('child_process').exec,
	require('./util'),
	require('./config.js'),
	function(error){

		if(error){
			console.log('error: process ' + process.pid + ' exit');
			process.exit(1);
		}else{
			console.log('success: process ' + process.pid + ' exit');
			process.exit(0);
		}
	}
);


