#!/usr/bin/env node

function dataPrompt(data, callback){

	console.log('starting util dataPrompt');

	var index = 0;
	var keys = Object.keys(data);
	var size = keys.length;

	if ( size > 0 ){

		var key = keys[index];
		var value = data[key];

		console.log('input ' + keys[index] );
		console.log('  defaultValue: ' + data[key]);
		
		process.stdin.resume();

		process.stdin.setEncoding('utf8');

		process.stdin.on('data', function (text) {

			if (text.length > 1){

				text = text.slice(0, text.length - 1);

				if (Number.isInteger(text)){

					data[key] = parseInt(text, 10);

				}else if( !isNaN(parseFloat(text)) ){

					data[key] = parseFloat(text);
				}else{
					data[key] = text;
				}
			}
			index++;

			if (index == size){
				
				console.log('util dataPromptdataPrompt success');

				process.stdin.pause();

				callback(null, data);
			}else{
				key = keys[index];
				value = data[key];

				console.log('input ' + keys[index]);
				console.log('  defaultValue: ' + data[key]);
			}
		});
	}else{
		console.log('util dataPromptdataPrompt success: (no data provided)');
	}
}

function deleteFolder(fs, path){

	console.log('starting util deleteFolder');

	if( fs.existsSync(path) ) {
	
		fs.readdirSync(path).forEach(function(file,index){
	
			var curPath = path + "/" + file;

			if(fs.lstatSync(curPath).isDirectory()) {
				
				deleteFolder(fs, curPath);
			} else {
				fs.unlinkSync(curPath);
			}
		});
		fs.rmdirSync(path);
	}
	console.log('util deleteFolder success');
}

function cloneRepo(exec, systemAction, dirName, repoName, repoURL, repoEXT, callback){

	console.log('starting util cloneRepo');

	exec(systemAction +
		' git cloneRepo ' +
		dirName + ' ' +
		repoName + ' ' +
		repoURL + ' ' +
		repoEXT,
		function (error, stdout, stderr) {

			if(stdout){
				console.log(stdout);
			}
			if (error) {
				console.log('util cloneRepo error: ' + error);
			} else {
				console.log('util cloneRepo success');
			}
			callback(error);
		}
	);
}

function write(fs, path, content, callback){

	console.log('starting util write');

	fs.writeFile(path, content, function(error) {
		
		if (error) {
			console.log('util write error:  ' + error.message); 
		} else {
			console.log('util write success');
		}
		callback(error);
	});
}

function writeExports(fs, path, exportObject, callback){

	console.log('starting util writeExports');

	write(fs, 
		path,
		'module.exports = ' + 
		JSON.stringify(exportObject, null, 2) + 
		';\n',
		function(error){

			if (error) {
				console.log('util writeExports error'); 
			} else {
				console.log('util writeExports success');
			}
			callback(error);
		}
	);
}

function npmInstall(exec, path, callback){

	console.log('starting util npmInstall');

	exec('cd ' + path + ' && npm install',

		function (error, stdout, stderr) {

			if(stdout){
				console.log(stdout);
			}
			if (error) {
				console.log('util npm install error: ' + error);
			} else {
				console.log('util npm install success');
			}
		callback(error);
	});
}

function setPermission(exec, path, owner, group, access, callback){

	console.log('starting util npmInstall');

	exec('chown -R ' + owner + ':' + group + ' ' + path +
		' && chmod -R ' + access + ' ' + path,
		function (error, stdout, stderr) {

			if(stdout){
				console.log(stdout);
			}
			if(error){
				console.log('util setPermission error: ' + error);
			}else{
				console.log('util setPermission success');
			}
			callback(error);
		}
	);
}

function systemServiceCall(exec, serviceName, serviceCall, callback){

	console.log('starting util systemServiceCall');

	exec('systemctl ' + serviceCall + ' ' + serviceName + '.service',
		function (error, stdout, stderr) {

			if(stdout){
				console.log(stdout);
			}
			if (error) {
				console.log('util systemServiceCall error: ' + error);
			} else {
				console.log('util systemServiceCall success');
			}
			callback(error);
		}
	);
}

function systemServiceReload(exec, callback){

	console.log('starting util systemServiceReload');

	exec('systemctl daemon-reload',
		function (error, stdout, stderr) {

			if(stdout){
				console.log(stdout);
			}
			if (error) {
				console.log('util systemServiceReload error: ' + error);
			} else {
				console.log('util systemServiceReload success');
			}
			callback(error);
		}
	);
}

function lint(exec, callback){

	console.log('starting util lint');

	console.log('starting lint jshint');

	exec('jshint . ./install ./init ./start ./stop ./reset ./status ./remove ./util --exclude ./node_modules',
		function (error, stdout, stderr) {

			if(stdout){
				console.log(stdout);
			}
			if (error) {
				console.log('lint jshint error: ' + error);
			
				callback(error);
			} else {
				console.log('lint jshint success');

				console.log('starting lint csslint');

				exec('csslint .',
				 	function (error, stdout, stderr) {

						if(stdout){
							console.log(stdout);
						}
						if (error) {
							console.log('lint csslint failure: ' + error);
						} else {
							console.log('lint csslint success');

							console.log('util lint success');
						}
						callback(error);
					}
				);
			}
		}
	);
}

module.exports.dataPrompt = dataPrompt;
module.exports.deleteFolder = deleteFolder;
module.exports.cloneRepo = cloneRepo;
module.exports.write = write;
module.exports.writeExports = writeExports;
module.exports.npmInstall = npmInstall;
module.exports.setPermission = setPermission;
module.exports.systemServiceCall = systemServiceCall;
module.exports.systemServiceReload = systemServiceReload;
module.exports.lint = lint;







